from hammett.types import State

ADDING_TASK = State('ADDING_TASK')

CHANGING_CLASS_NAME = State('CHANGING_CLASS_NAME')

CHANGING_TASK_DESCRIPTION = State('CHANGING_TASK_DESCRIPTION')

CHANGING_CLASS_PASSWORD = State('CHANGING_CLASS_PASSWORD')

CHANGING_ITEM_NAME = State('CHANGING_ITEM_NAME')

CHANGING_ITEM_ROD_NAME = State('CHANGING_ITEM_ROD_NAME')

CHANGING_ITEM_GROUPS = State('CHANGING_ITEM_GROUPS')

CHANGING_ITEM_EMOJI = State('CHANGING_ITEM_EMOJI')

CREATING_ITEM_EMOJI = State('CREATING_ITEM_EMOJI')

CREATING_ITEM_NAME = State('CREATING_ITEM_NAME')

CREATING_ITEM_ROD_NAME = State('CREATING_ITEM_ROD_NAME')

CREATING_ITEM_GROUP = State('CREATING_ITEM_GROUP')

CREATING_CLASS = State('CREATING_CLASS')

ADDING_PASSWORD_TO_CLASS = State('ADDING_PASSWORD_TO_CLASS')

WRITING_PASSWORD_TO_JOIN = State('WRITING_PASSWORD_TO_JOIN')