name: Bug report template
description: Create a bud report to help School Tasker improve
title: '[Bug]: '
labels: ["bug", "help wanted", "invalid"]
assignees: TheDanskiSon09
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: True
  - type: textarea
    id: what-happened
    attributes:
      label: Please, send description and photo of bug
      description: Also tell us, what did you expect to happen?
      placeholder: Tell and show us what you see!
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/TheDanskiSon09/School-Tasker/blob/main/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
