name: Feature Request
description: Suggest an idea for this project
title: '[Idea]: '
labels: ["enhancements"]
assignees: TheDanskiSon09
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this feature request!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: True
  - type: textarea
    id: what-happened
    attributes:
      label: What you want to see in School Tasker?
      description: A clear and concise description of what the problem is. Ex. Im always frustrated when [...]
      placeholder: Tell and show us what you want to see!
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/TheDanskiSon09/School-Tasker/blob/main/CODE_OF_CONDUCT.md). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true
